
Vagrant.configure("2") do |config|
  config.omnibus.chef_version = '11.8.2'
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 8983, host: 8983
  config.vm.provision :shell, :inline => "sudo apt-get update"
  config.vm.synced_folder "../airbitz", "/airbitz", :create => true
  config.vm.synced_folder "../staging", "/staging", :create => true
end

# -*- mode: ruby -*-
# vi: set ft=ruby :

