#!/usr/bin/env python

import os
import subprocess

basename = os.path.basename(os.getcwd())
subprocess.call(["curl", "http://localhost:8000/api/v1/repo/sync/{0}".format(basename)], stdout=False, stderr=False)
