#!/bin/sh

GITCMD="/usr/bin/git"
NULLSHA="0000000000000000000000000000000000000000"
MAXSIZE="$(( 1024 * 1024 + 1024 * 256 ))" # 1.5MB limit on file size
MAX_REPO_SIZE="$(( 1024 * 1024 * 300 ))" # 300 MB
EXIT=0

# Calculate current repository size
REPO_TOTAL=$(($(du . -cks | grep -i Total | awk '{print $1}') * 1024))

while read oldref newref refname; do
    # Skip branch deletions
    if [ "${newref}" = "${NULLSHA}" ]; then
        continue;
    fi

    # Set oldref properly if this is branch creation.
    if [ "${oldref}" = "${NULLSHA}" ]; then
        oldref="HEAD"
    fi

    for file in $($GITCMD diff --stat --name-only --diff-filter=ACMRT ${oldref}..${newref}); do
        size=$($GITCMD cat-file -s ${newref}:${file})
        if [ ! -z ${size} ]; then
            REPO_TOTAL=$(($REPO_TOTAL + $size))
            if [ "${REPO_TOTAL}" -gt "${MAX_REPO_SIZE}" ]; then
                echo "ERROR: repository is too big."
                EXIT=1
            fi
            if [ "${size}" -gt "${MAXSIZE}" ]; then
                echo "ERROR: ${file} larger than ${MAXSIZE}."
                EXIT=1
            fi
        fi
    done
done

if [ "${EXIT}" = "1" ]; then
  echo "ERROR: Your commit has been blocked due files size restrictions."
  exit ${EXIT}
fi
